### PR TITLE
Add ability to filter meeting list based on specific contact / whether to display all meetings

### LINKED ISSUE #10: As a well-connected salesman, I can see a history of the number of contacts made with someone
... so that I can determine if this contact is worth investing more time into.

- Implement `meeting list [c/CONTACT_INDEX] [a/]`

### PR DESCRIPTION
**Pull request by sebastiantoh**
Closes #10

Changes:
- Added `meeting list [c/CONTACT_INDEX] [a/]`
  - By default, only upcoming meetings are displayed (aka `meeting list`)
- Updated UI so that past meetings have lower opacity

Meeting list

### CODE REVIEW

**Review by hakujitsu — CHANGES_REQUESTED** [review]
When testing, something interesting happened: I created an upcoming meeting and used `meeting list` to display all meetings. After the meeting was over, I retyped `meeting list`, and the meeting was greyed out, but still present. I think there's a need to refresh the contents of the list in this case?

Other than this issue, the code looks good! Great decision to use ListMeetingDescriptor

**Comment by sebastiantoh** [comment]
> 
> 
> When testing, something interesting happened: I created an upcoming meeting and used `meeting list` to display all meetings. After the meeting was over, I retyped `meeting list`, and the meeting was greyed out, but still present. I think there's a need to refresh the contents of the list in this case?
> 
> Other than this issue, the code looks good! Great decision to use ListMeetingDescriptor

Great catch, fixed! Thank you!

**Comment by hakujitsu** [comment]
Hmm, I pulled again to test but the meeting still remains greyed out for me and doesn't disappear, could you check again?

**Comment by sebastiantoh** [comment]
That's weird. 

Just to confirm, the steps to reproduce are as follows: (assuming current time is 26 Oct 2020, 18:32)
1. Open up app
2. Execute `meeting add c/1 m/fnakldsnlk d/2020-10-26 18:32 du/1`
3. Execute `meeting list`
4. Wait for 18:34
5. Execute `meeting list`
    - Newly created meeting should disappear, but appears in the list (although greyed out)?

**Comment by hakujitsu** [comment]
My bad, I tried again and it seems to be fixed. Will merge!

**Review by hakujitsu — APPROVED** [review]

**Pull request merged**
